#!/usr/bin/env python3
"""Generate the client-side DRIP-score JavaScript snippet for Qualtrics.

Reads ../../../response_verification/drip_item_pairs.tsv (the single source
of truth also used by verify_responses.py's check_drip()) and prints a
ready-to-paste "Add JavaScript" snippet that computes the same score --
sum of |item1 - item2| over the 15 pairs, each reverse-keyed item recoded
6-x first -- entirely client-side, using the current (non-deprecated)
Qualtrics.SurveyEngine.setJSEmbeddedData() API. See ../../../docs/
qualtrics-part2-wiring.md for where this snippet goes.

Regenerate and re-paste this whenever drip_item_pairs.tsv changes.

Usage:
    python3 gen_drip_js.py
"""
import csv
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent
REPO_ROOT = SKILL_DIR.parent.parent.parent
PAIRS_FILE = REPO_ROOT / "response_verification" / "drip_item_pairs.tsv"


def load_pairs():
    with open(PAIRS_FILE, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        pairs = []
        for row in reader:
            pairs.append({
                "item1": int(row["Item1"]), "item2": int(row["Item2"]),
                "reverse1": row["Reverse1"].strip().lower() == "true",
                "reverse2": row["Reverse2"].strip().lower() == "true",
            })
    if len(pairs) != 15:
        raise SystemExit(f"expected 15 DRIP pairs, found {len(pairs)}")
    return pairs


def piped(item_num):
    return f"${{q://QID2/SelectedChoicesRecode/{item_num}}}"


def recode_expr(var_name, reverse):
    return f"(6 - {var_name})" if reverse else var_name


def render(pairs):
    lines = []
    lines.append("// DRIP score (Ruchensky, Edens, & Donnellan, 2025) -- generated by")
    lines.append("// .claude/skills/bfi2-qsf-splitter/gen_drip_js.py from drip_item_pairs.tsv.")
    lines.append("// Paste into the last question's 'Add JavaScript' panel (Advanced Options)")
    lines.append("// in the Survey-Flow block that runs AFTER the BFI-2+RPS content block.")
    lines.append("Qualtrics.SurveyEngine.addOnload(function () {")
    lines.append("    var drip = 0;")
    for i, p in enumerate(pairs, start=1):
        v1 = f"v{i}a"
        v2 = f"v{i}b"
        lines.append(f"    var {v1} = parseInt(\"{piped(p['item1'])}\", 10);")
        lines.append(f"    var {v2} = parseInt(\"{piped(p['item2'])}\", 10);")
        lines.append(f"    drip += Math.abs({recode_expr(v1, p['reverse1'])} - {recode_expr(v2, p['reverse2'])});")
    lines.append("    // BFI-2's ForceResponse is a soft prompt (RequestResponse), not a hard")
    lines.append("    // requirement, so a skipped item is possible -- parseInt(\"\", 10) is NaN,")
    lines.append("    // which would poison the whole sum. Sentinel to -1 (a normal finite number")
    lines.append("    // outside the server's [0, cutoff) pass range -- see qualtrics_router.py)")
    lines.append("    // rather than let a literal NaN reach the Web Service call: the server")
    lines.append("    // treats -1 as a well-formed-but-failing score, same as a real score at or")
    lines.append("    // above cutoff -- a normal, tracked review verdict (200, not an error) --")
    lines.append("    // whereas a non-finite value is hard-rejected (422): it can't be recorded")
    lines.append("    // as a meaningful score at all, so there's no review verdict to create it")
    lines.append("    // under. Keeping NaN off the wire entirely is simpler than relying on the")
    lines.append("    // server to handle it well, not a workaround for a server-side bug.")
    lines.append("    if (isNaN(drip)) { drip = -1; }")
    lines.append("    // Embedded data field must be declared in Survey Flow as '__js_drip_score'")
    lines.append("    // (the '__js_' prefix is required by setJSEmbeddedData; a later plain")
    lines.append("    // Embedded Data element copies it to 'drip_score' via piped text -- see")
    lines.append("    // docs/qualtrics-part2-wiring.md).")
    lines.append("    Qualtrics.SurveyEngine.setJSEmbeddedData(\"drip_score\", drip);")
    lines.append("});")
    return "\n".join(lines)


def main():
    pairs = load_pairs()
    print(render(pairs))


if __name__ == "__main__":
    main()
