#!/usr/bin/env python3
"""Generate the client-side DRIP-score JavaScript snippet for Qualtrics.

Reads ../../../response_verification/drip_item_pairs.tsv (the single source
of truth also used by verify_responses.py's check_drip()) and prints a
ready-to-paste "Add JavaScript" snippet that computes the same score --
sum of |item1 - item2| over the 15 pairs, each reverse-keyed item recoded
6-x first -- entirely client-side, using the current (non-deprecated)
Qualtrics.SurveyEngine.setJSEmbeddedData() API. See ../../../docs/
qualtrics-part2-wiring.md for where this snippet goes.

Regenerate and re-paste this whenever drip_item_pairs.tsv changes.

Usage:
    python3 gen_drip_js.py
"""
import csv
import json
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent
REPO_ROOT = SKILL_DIR.parent.parent.parent
PAIRS_FILE = REPO_ROOT / "response_verification" / "drip_item_pairs.tsv"
FULL_QSF = REPO_ROOT / "output" / "BFI-2_Full.qsf"

sys.path.insert(0, str(SKILL_DIR))
# split_bfi2 (not verify_responses) deliberately -- it's stdlib-only, and
# this script must stay stdlib-only too (verify_responses.py needs
# pandas/numpy/scipy; the rest of the repo, including this script, doesn't).
from split_bfi2 import normalize_text, load_master_mapping  # noqa: E402


def load_full_form_item_meta():
    """item number -> {domain, facet, reverse}, via QID2's real Choices."""
    mapping = load_master_mapping()
    qsf = json.loads(FULL_QSF.read_text(encoding="utf-8"))
    sq = next(e for e in qsf["SurveyElements"]
              if e["Element"] == "SQ" and e["PrimaryAttribute"] == "QID2")
    return {int(cid): mapping[normalize_text(c["Display"])]
            for cid, c in sq["Payload"]["Choices"].items()}


def cross_validate_pairs(pairs, item_meta):
    """Abort if a pair's facet/domain/reverse disagrees with master_mapping.json.

    Same check verify_responses.py's cross_validate_pairs runs -- reused
    here (not imported, to stay off the pandas dependency) because a
    corrupted pair getting baked into this script's generated client-side
    JS is worse than the same corruption in the offline detector: it ends
    up permanently pasted into a live Qualtrics survey, harder to catch
    after the fact.
    """
    problems = []
    for i, p in enumerate(pairs, start=1):
        for side in ("1", "2"):
            item = p[f"item{side}"]
            meta = item_meta.get(item)
            if meta is None:
                problems.append(f"pair {i}: item {item} not present in the Full form")
                continue
            if bool(meta["reverse"]) != p[f"reverse{side}"]:
                problems.append(
                    f"pair {i}: item {item} reverse={meta['reverse']} in "
                    f"master_mapping.json but reverse{side}={p[f'reverse{side}']} in the TSV")
            if meta["facet"] != p["facet"]:
                problems.append(
                    f"pair {i}: item {item} facet {meta['facet']!r} in "
                    f"master_mapping.json but table facet {p['facet']!r}")
            if meta["domain"] != p["domain"]:
                problems.append(
                    f"pair {i}: item {item} domain {meta['domain']!r} in "
                    f"master_mapping.json but table domain {p['domain']!r}")
    if problems:
        raise SystemExit(
            "drip_item_pairs.tsv disagrees with master_mapping.json:\n  "
            + "\n  ".join(problems))


def load_pairs():
    with open(PAIRS_FILE, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        pairs = []
        for row in reader:
            pairs.append({
                "item1": int(row["Item1"]), "item2": int(row["Item2"]),
                "reverse1": row["Reverse1"].strip().lower() == "true",
                "reverse2": row["Reverse2"].strip().lower() == "true",
                "domain": row["Domain"], "facet": row["Facet"],
            })
    if len(pairs) != 15:
        raise SystemExit(f"expected 15 DRIP pairs, found {len(pairs)}")
    seen_items = set()
    for p in pairs:
        for item in (p["item1"], p["item2"]):
            if item in seen_items:
                raise SystemExit(f"item {item} appears in more than one DRIP pair")
            seen_items.add(item)
    cross_validate_pairs(pairs, load_full_form_item_meta())
    return pairs


def piped(item_num):
    return f"${{q://QID2/SelectedChoicesRecode/{item_num}}}"


def recode_expr(var_name, reverse):
    return f"(6 - {var_name})" if reverse else var_name


def render(pairs):
    lines = []
    lines.append("// DRIP score (Ruchensky, Edens, & Donnellan, 2025) -- generated by")
    lines.append("// .claude/skills/bfi2-qsf-splitter/gen_drip_js.py from drip_item_pairs.tsv.")
    lines.append("// Paste into the last question's 'Add JavaScript' panel (Advanced Options)")
    lines.append("// in the Survey-Flow block that runs AFTER the BFI-2+RPS content block.")
    lines.append("Qualtrics.SurveyEngine.addOnload(function () {")
    lines.append("    var drip = 0;")
    for i, p in enumerate(pairs, start=1):
        v1 = f"v{i}a"
        v2 = f"v{i}b"
        lines.append(f"    var {v1} = parseInt(\"{piped(p['item1'])}\", 10);")
        lines.append(f"    var {v2} = parseInt(\"{piped(p['item2'])}\", 10);")
        lines.append(f"    drip += Math.abs({recode_expr(v1, p['reverse1'])} - {recode_expr(v2, p['reverse2'])});")
    lines.append("    // BFI-2's ForceResponse is a soft prompt (RequestResponse), not a hard")
    lines.append("    // requirement, so a skipped item is possible -- parseInt(\"\", 10) is NaN,")
    lines.append("    // which would poison the whole sum. Sentinel to -1 (a normal finite number")
    lines.append("    // outside the server's [0, cutoff) pass range -- see qualtrics_router.py)")
    lines.append("    // rather than let a literal NaN reach the Web Service call: the server")
    lines.append("    // treats -1 as a well-formed-but-failing score, same as a real score at or")
    lines.append("    // above cutoff -- a normal, tracked review verdict (200, not an error) --")
    lines.append("    // whereas a non-finite value is hard-rejected (422): it can't be recorded")
    lines.append("    // as a meaningful score at all, so there's no review verdict to create it")
    lines.append("    // under. Keeping NaN off the wire entirely is simpler than relying on the")
    lines.append("    // server to handle it well, not a workaround for a server-side bug.")
    lines.append("    if (isNaN(drip)) { drip = -1; }")
    lines.append("    // Embedded data field must be declared in Survey Flow as '__js_drip_score'")
    lines.append("    // (the '__js_' prefix is required by setJSEmbeddedData; a later plain")
    lines.append("    // Embedded Data element copies it to 'drip_score' via piped text -- see")
    lines.append("    // docs/qualtrics-part2-wiring.md).")
    lines.append("    Qualtrics.SurveyEngine.setJSEmbeddedData(\"drip_score\", drip);")
    lines.append("});")
    return "\n".join(lines)


def main():
    pairs = load_pairs()
    print(render(pairs))


if __name__ == "__main__":
    main()
